version: 2.1

jobs:
  docker_layer_caching:
    docker:
    - image: cimg/base:stable
    parallelism: 10
    steps:
    - run: which docker
    - run: docker -v
    - run:
        name: process record 
        command: |
          while true; do
            date
            ps auxwwf
            echo "======"
          done
        background: true
    - run: sleep 500
    - setup_remote_docker:
        docker_layer_caching: true
    - run: ssh remote-docker free -h
    - run: ssh remote-docker lscpu
    - run: docker version
    - run:
        name: Build a really docker image
        command: |
          dockerfile=Dockerfile
          echo "FROM alpine:latest" > $dockerfile
          echo "RUN mkdir momo" >> $dockerfile
          echo "RUN echo hello" >> $dockerfile
          echo "RUN apk update && apk add bash vim openssl ruby" >> $dockerfile
          docker build -f $dockerfile --tag throwaway:$CIRCLE_BUILD_NUM .
    - run: |
        mkdir mem
        docker run -v $(pwd)/mem:/momo throwaway:$CIRCLE_BUILD_NUM touch momo/awa.txt
        ls -la mem
  machine_dlc:
    machine: true
    steps:
    - run:
        name: Retrive logs
        command: journalctl -f --no-pager
        background: true
    - run: which docker
    - run: docker -v
    - run: sleep 500
    - run:
        name: Build a really docker image
        command: |
          dockerfile=Dockerfile
          echo "FROM alpine:latest" > $dockerfile
          echo "RUN echo hello" >> $dockerfile
          docker build -f $dockerfile --tag throwaway:$CIRCLE_BUILD_NUM .
          docker run --rm throwaway:$CIRCLE_BUILD_NUM
    - run: docker version
    - run:
        name: Retrive logs
        command: journalctl --no-pager
        when: always
  nyancat:
    machine: true
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y nyancat
      - run:
          name: nyan
          environment:
            TERM: xterm
          command: nyancat -W 60 -H 30 -f 100
    
workflows:
  version: 2
  vm_jobs:
    jobs:
      - docker_layer_caching
      - machine_dlc
      - nyancat
